services:
  migrate:
    image: !reset null
    build:
      context: ./deploy/docker/migrate
  collector:
    image: !reset null
    build:
      context: ./collector
      dockerfile: Dockerfile
  api:
    image: !reset null
    build:
      context: ./api
      dockerfile: Dockerfile
  dashboard:
    image: !reset null
    build:
      context: ./dashboard
      dockerfile: Dockerfile
