import type { TraceDetail } from './interfaces';
import type { TraceDetailId, SpanDetailId, SessionId } from './ids';

export const TRACE_DETAIL: TraceDetail = {
  id:           "t_a9f2_eb7c" as TraceDetailId,
  agent:        "rewrite-message",
  version:      "v2.4.1",
  status:       "failed",
  startedAt:    "Apr 18, 2026 · 7:41:17 AM",
  endedAt:      "Apr 18, 2026 · 7:41:22 AM",
  duration:     4823,
  totalCost:    0.0012,
  inputTokens:  3420,
  outputTokens: 128,
  cachedTokens: 1280,
  model:        "claude-haiku-4-5",
  provider:     "anthropic",
  user:         "user_38291",
  sessionId:    "sess_xv2h81" as SessionId,
  environment:  "production",
  region:       "us-east-1",
  sdk:          "tracium-node @ 0.8.2",
  input: `{
  "thread_id": "th_9822",
  "message": "Can you tone this down and make it more professional?",
  "draft": "hey team — this is taking forever and it's kinda ridiculous",
  "audience": "internal-slack",
  "max_words": 60
}`,
  output: null,
  tags: ["retry", "high-latency", "slack-integration"],
  error: {
    type:    "rate_limit_exceeded",
    message: "Rate limit of 40 requests per minute exceeded for model claude-haiku-4-5. Retry after 23 seconds.",
    code:    "429",
    stack: `RateLimitError: 429 rate_limit_exceeded\n  at Anthropic.request (anthropic-sdk/dist/core.js:214:23)\n  at Anthropic.messages.create (anthropic-sdk/dist/resources/messages.js:48:17)\n  at async rewriteMessage (src/agents/rewrite-message.ts:82:20)\n  at async Agent.run (tracium/runtime.ts:341:14)`,
  },
  spans: [
    {
      id: "s1" as SpanDetailId, name: "rewrite-message", type: "agent", start: 0, duration: 4823, depth: 0,
      cost: 0, tokens: 0, inputTokens: 0, outputTokens: 0, subtreeCost: 0.0012, childCount: 6, status: "failed",
      attributes: { "agent.version": "v2.4.1", "user.id": "user_38291", "tags": "retry,high-latency" },
      input: "Rewrite draft for audience internal-slack, max 60 words.",
      output: "(failed — rate_limit_exceeded on retry)",
      error: {
        type:    "AgentRunError",
        message: "Agent aborted: the retry LLM call failed and no fallback was configured.",
        code:    "",
        stack:   "",
      },
    },
    {
      id: "s2" as SpanDetailId, name: "load-context", type: "tool", start: 12, duration: 284, depth: 1,
      cost: 0, tokens: 0, status: "ok",
      attributes: { "tool.name": "load-context", "db.system": "postgres", "rows": "14" },
      input: `{ "thread_id": "th_9822" }`,
      output: `{ "rows": 14, "bytes": 8822 }`,
    },
    {
      id: "s3" as SpanDetailId, name: "fetch-thread-history", type: "tool", start: 298, duration: 412, depth: 1,
      cost: 0, tokens: 0, status: "ok",
      attributes: { "tool.name": "slack.history", "http.status": "200", "items": "42" },
      input: `{ "thread_id": "th_9822", "limit": 50 }`,
      output: `{ "messages": 42, "truncated": false }`,
    },
    {
      id: "s4" as SpanDetailId, name: "build-prompt", type: "internal", start: 714, duration: 18, depth: 1,
      cost: 0, tokens: 0, status: "ok",
      attributes: { "prompt.template": "rewrite.v3", "context.tokens": "2890" },
      input: "template=rewrite.v3",
      output: "prompt_tokens=3420",
    },
    {
      id: "s5" as SpanDetailId, name: "llm.complete", type: "llm", start: 732, duration: 2104, depth: 1,
      cost: 0.0008, tokens: 2410, inputTokens: 2282, outputTokens: 128, status: "ok",
      attributes: {
        "llm.model": "claude-haiku-4-5", "llm.provider": "anthropic",
        "llm.temperature": "0.3", "llm.max_tokens": "512",
        "usage.input_tokens": "2282", "usage.output_tokens": "128", "usage.cache_read": "1280",
      },
      input: "System: You are a professional tone rewriter...\nUser: Rewrite: 'hey team...'",
      output: "Team — the current timeline is significantly longer than expected, and it's creating friction.",
      availableTools: [
        { name: "tone.classify",     used: true,  description: "Returns a softmax over five tone labels (formal, casual, urgent, frustrated, neutral)." },
        { name: "style_guide.fetch", used: false, description: "Retrieves the workspace's writing style guide entries by audience tag." },
        { name: "draft.refine",      used: false, description: "One-shot LLM refinement pass on a candidate draft against a target tone." },
        { name: "users.lookup",      used: false, description: "Resolves a Slack user ID to a profile (name, role, timezone) for personalisation." },
        { name: "memory.recall",     used: false, description: "Searches long-term agent memory for prior interactions with this user." },
        { name: "rate_limit.check",  used: false, description: "Returns the user's remaining rewrite quota and reset time." },
        { name: "pii.redact",        used: false, description: "Strips emails, phone numbers, and SSNs from a string before logging." },
      ],
    },
    {
      id: "s6" as SpanDetailId, name: "validate-output", type: "internal", start: 2836, duration: 42, depth: 1,
      cost: 0, tokens: 0, status: "ok",
      attributes: { "check": "word-count", "max_words": "60", "actual_words": "18" },
      input: "text=Team — the current timeline...",
      output: "valid=true",
    },
    {
      id: "s7" as SpanDetailId, name: "llm.complete (retry)", type: "llm", start: 2878, duration: 1920, depth: 1,
      cost: 0.0004, tokens: 1138, inputTokens: 1138, outputTokens: 0, status: "failed",
      attributes: {
        "llm.model": "claude-haiku-4-5", "llm.provider": "anthropic",
        "retry.attempt": "2", "retry.reason": "validation_softfail",
      },
      input: "System: Refine previous output for stricter tone match...\nUser: (abbreviated)",
      output: "(no output — 429 rate_limit_exceeded)",
      error: {
        type:    "rate_limit_exceeded",
        message: "Rate limit of 40 requests per minute exceeded for model claude-haiku-4-5. Retry after 23 seconds.",
        code:    "429",
        stack:   "",
      },
      availableTools: [
        { name: "style_guide.fetch", used: false, description: "Retrieves the workspace's writing style guide entries by audience tag." },
        { name: "draft.refine",      used: false, description: "One-shot LLM refinement pass on a candidate draft against a target tone." },
        { name: "memory.recall",     used: false, description: "Searches long-term agent memory for prior interactions with this user." },
      ],
    },
  ],
};
