/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List traces
         * @description Returns a paginated list of traces for the authenticated tenant. Results are ordered by start_time_ms descending.
         */
        get: operations["listTraces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/traces/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a trace by ID
         * @description Returns a single trace including its full span list.
         */
        get: operations["getTrace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics/kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Overview KPIs
         * @description Returns the four headline metrics (total cost, agent runs, p95 latency, error rate) for the selected range, each with its change versus the equal-length preceding period.
         */
        get: operations["getOverviewKpis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics/cost-series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cost over time
         * @description Total cost per time bucket across the range.
         */
        get: operations["getCostSeries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics/latency-series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latency over time
         * @description p50/p95/p99 of span duration (ms) per time bucket across the range.
         */
        get: operations["getLatencySeries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics/error-series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Failures over time
         * @description Failed-vs-total run counts per time bucket across the range — the "Failures by day" strip.
         */
        get: operations["getErrorSeries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics/top-agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Top agents by cost
         * @description The highest-spending agents (trace root names) in the range, ordered by cost descending.
         */
        get: operations["getTopAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Agent activity list
         * @description Every active agent in the range with its run count, total spend, mean run latency, error rate, and call-count sparkline — the data behind the Agents page. Ordered by call count descending; sorting and filtering are done client-side. avg_latency_ms is 0 for long windows served from the daily rollup, where per-trace durations are not retained.
         */
        get: operations["listAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics/agents/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Agent detail
         * @description One agent's detail-page payload: its headline metrics over the range plus the tool surface from its most recent run. Span-backed only — there is no agent-config store, so runtime params (temperature, retries, version, owner, …) are not served. A raw-window feature: ranges longer than 30d (90d, 1y) are rejected with a 400, since per-agent latency cannot be derived from the daily rollup.
         */
        get: operations["getAgentDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics/failures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent failures
         * @description The agents with the most errored runs in the range. The response total counts every failed run in the window, not just the listed agents.
         */
        get: operations["getFailures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check
         * @description Returns 200 when the API process is running. Does not verify downstream dependencies (use /v1/ready for that).
         */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness check
         * @description Returns 200 when the API is ready to serve traffic (database connections healthy). Returns 503 when not ready.
         */
        get: operations["readinessCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Span: {
            /** @description Globally unique identifier for the trace this span belongs to. */
            trace_id: string;
            /** @description Globally unique identifier for this span. */
            span_id: string;
            /** @description span_id of the parent span, if this is a child span. */
            parent_span_id?: string;
            /** @description Human-readable name for this span. */
            name: string;
            /** @description Unix epoch milliseconds when the span started. */
            start_time_ms?: number;
            /** @description Unix epoch milliseconds when the span ended. */
            end_time_ms?: number;
            /** @description Duration of the span in milliseconds. */
            duration_ms?: number;
            /** @description The model name as reported in gen_ai.request.model. */
            model?: string;
            /** @description Why the model stopped generating. */
            finish_reason?: string;
            /** @description Number of input tokens consumed. */
            input_tokens?: number;
            /** @description Number of output tokens generated. */
            output_tokens?: number;
            /** @description Computed cost in USD for this span. */
            cost_usd?: number;
            /** @description Tenant identifier. */
            tenant_id?: string;
            /** @description Canonical model id after alias resolution. */
            model_normalized?: string;
            /** @description Schema version of this span record. */
            schema_version?: number;
            /** @description Added in schema v2. Short error class or type. */
            error_type?: string;
            /** @description Added in schema v2. Human-readable error message if the span failed. */
            error_message?: string;
            /**
             * @description Normalized span role, derived by the collector from instrumentation attributes (OpenInference openinference.span.kind, Traceloop traceloop.span.kind, or the OTel GenAI gen_ai.operation.name). Optional: omitted when the collector could not classify the span, in which case consumers infer the role from the span's context.
             * @enum {string}
             */
            kind?: "agent" | "llm" | "tool" | "chain" | "retriever" | "embedding";
        };
        Trace: {
            /** @description Globally unique identifier for this trace. */
            trace_id: string;
            /** @description Human-readable name for the trace. */
            name?: string;
            /** @description Unix epoch milliseconds when the trace started. */
            start_time_ms?: number;
            /** @description Unix epoch milliseconds when the trace ended. */
            end_time_ms?: number;
            /** @description Total duration in milliseconds. */
            duration_ms?: number;
            /** @description Tenant identifier. */
            tenant_id?: string;
            /** @description Total number of spans in this trace. */
            span_count?: number;
            /** @description True if any span in this trace recorded an error. */
            has_error?: boolean;
            /** @description Sum of cost_usd across all spans in this trace. */
            total_cost_usd?: number;
            /** @description Schema version of this trace record. */
            schema_version?: number;
        };
        TraceDetail: components["schemas"]["Trace"] & {
            /** @description All spans belonging to this trace, ordered by start_time_ms ascending. */
            spans: components["schemas"]["Span"][];
        };
        ErrorResponse: {
            /** @description Machine-readable error code (e.g. NOT_FOUND, UNAUTHORIZED, INVALID_REQUEST). */
            code: string;
            /** @description Human-readable description of the error. */
            message: string;
        };
        PaginatedTraceResponse: {
            /** @description The traces on this page. */
            items: components["schemas"]["Trace"][];
            /** @description Total number of matching traces across all pages. */
            total: number;
            /** @description Current page number (1-based). */
            page: number;
            /** @description Number of items per page. */
            page_size: number;
            /** @description True if there are more pages after this one. */
            has_more: boolean;
        };
        Kpi: {
            /** @description Raw metric value (USD, count, ms, or fraction depending on the KPI). */
            value: number;
            /** @description Fractional change versus the preceding period (0.12 == +12%). */
            delta: number;
            /**
             * @description Whether the change is favourable, given the metric's direction.
             * @enum {string}
             */
            delta_type: "good" | "bad" | "neutral";
        };
        KpiSet: {
            /** @description Total cost in USD. */
            cost: components["schemas"]["Kpi"];
            /** @description Agent runs (distinct traces). */
            runs: components["schemas"]["Kpi"];
            /** @description p95 trace duration in ms. */
            latency_p95: components["schemas"]["Kpi"];
            /** @description Fraction of traces with an error. */
            error_rate: components["schemas"]["Kpi"];
        };
        CostBucket: {
            /** @description Bucket start, Unix epoch milliseconds. */
            bucket_ms: number;
            /** @description Total cost in USD within the bucket. */
            value: number;
            /** @description True if the bucket exceeds three times the window's median. */
            anomaly: boolean;
        };
        ErrorBucket: {
            /** @description Bucket start, Unix epoch milliseconds. */
            bucket_ms: number;
            /** @description Runs that errored within the bucket. */
            errors: number;
            /** @description Total runs that started within the bucket. */
            total: number;
        };
        LatencyBucket: {
            /** @description Bucket start, Unix epoch milliseconds. */
            bucket_ms: number;
            /** @description Median span duration in the bucket, ms. Null when no runs fell in the bucket (latency is undefined rather than 0). */
            p50: number | null;
            /** @description 95th-percentile span duration in the bucket, ms. Null when no runs fell in the bucket. */
            p95: number | null;
            /** @description 99th-percentile span duration in the bucket, ms. Null when no runs fell in the bucket. */
            p99: number | null;
        };
        AgentCost: {
            /** @description Agent name (the trace root span name). */
            name: string;
            /** @description Total cost in USD over the window. */
            cost: number;
            /** @description Number of runs (traces) for this agent. */
            calls: number;
            /** @description Call count per time bucket across the window, oldest first and zero-filled, aligned to a shared axis for the usage sparkline. */
            trend: number[];
        };
        Agent: {
            /** @description Agent name (the trace root span name). */
            name: string;
            /** @description Number of runs (traces) for this agent over the window. */
            calls: number;
            /** @description Total cost in USD over the window. */
            cost: number;
            /** @description Mean end-to-end run duration in milliseconds. 0 for long windows served from the daily rollup, where per-trace durations are not retained. */
            avg_latency_ms: number;
            /** @description Fraction of the agent's runs that errored (0–1). */
            error_rate: number;
            /** @description Call count per time bucket across the window, oldest first and zero-filled, aligned to a shared axis for the row sparkline. */
            trend: number[];
            /** @description The agent's most recent trace in the window, for deep-linking a row to its trace detail. Empty for long windows served from the daily rollup, which does not retain trace identity. */
            last_trace_id: string;
        };
        AvailableTool: {
            /** @description Tool name as offered to the model. */
            name: string;
            /** @description Whether the agent invoked this tool in the sampled run. */
            used: boolean;
            /** @description Human-readable description of what the tool does. */
            description?: string;
        };
        AgentDetail: {
            /** @description Agent name (the trace root span name). */
            name: string;
            /** @description Number of runs (traces) for this agent over the window. */
            calls: number;
            /** @description Total cost in USD over the window. */
            cost: number;
            /** @description Mean end-to-end run duration in milliseconds. */
            avg_latency_ms: number;
            /** @description p95 end-to-end run duration in milliseconds, or null when undefined (no runs in the window). */
            p95_latency_ms: number | null;
            /** @description Fraction of the agent's runs that errored (0–1). */
            error_rate: number;
            /** @description Total input tokens across the agent's runs over the window. */
            input_tokens: number;
            /** @description Total output tokens across the agent's runs over the window. */
            output_tokens: number;
            /** @description The agent's most-used normalized model id over the window. */
            model: string;
            /** @description Provider inferred from the model id; empty when unrecognised. */
            provider: string;
            /** @description The agent's tool surface — the union of available_tools from its most recent run. Empty when content/tool capture is disabled. */
            tools: components["schemas"]["AvailableTool"][];
            /** @description The agent's most recent trace in the window, for deep-linking. */
            last_trace_id: string;
        };
        Failure: {
            /** @description Agent name (the trace root span name). */
            agent: string;
            /** @description Number of failed runs. */
            count: number;
            /** @description Fraction of this agent's runs that failed. */
            pct: number;
            /** @description Most common error_type among this agent's failed runs. */
            top_error: string;
        };
        PaginatedCostBucketResponse: {
            items: components["schemas"]["CostBucket"][];
            total: number;
            page: number;
            page_size: number;
        };
        PaginatedErrorBucketResponse: {
            items: components["schemas"]["ErrorBucket"][];
            total: number;
            page: number;
            page_size: number;
        };
        PaginatedLatencyBucketResponse: {
            items: components["schemas"]["LatencyBucket"][];
            total: number;
            page: number;
            page_size: number;
        };
        PaginatedAgentCostResponse: {
            items: components["schemas"]["AgentCost"][];
            total: number;
            page: number;
            page_size: number;
        };
        PaginatedAgentResponse: {
            items: components["schemas"]["Agent"][];
            total: number;
            page: number;
            page_size: number;
        };
        PaginatedFailureResponse: {
            items: components["schemas"]["Failure"][];
            /** @description Total failed runs in the window (not just the listed agents). */
            total: number;
            page: number;
            page_size: number;
        };
    };
    responses: never;
    parameters: {
        /** @description Time window for the metric. Defaults to 7d. 24h is bucketed hourly; 7d/30d/90d/1y daily. Ranges longer than 30d (90d, 1y) are served from the daily rollup, so latency percentiles are not available for them. */
        Range: "24h" | "7d" | "30d" | "90d" | "1y";
        /** @description Optional business filter (the operator's end-client). Empty means all clients. */
        TenantFilter: string;
        /** @description Optional: restrict the metric to a single agent (the trace root name), powering the agent detail page's charts. Agent-scoped metrics are a raw-window feature — ranges longer than 30d (90d, 1y) are rejected with a 400, since per-agent latency cannot be derived from the daily rollup. */
        AgentFilter: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listTraces: {
        parameters: {
            query?: {
                /** @description Filter by tenant ID (admin use — regular callers are scoped to their own tenant). */
                tenant_id?: string;
                /** @description Filter traces that contain at least one span using this model (normalized model id). */
                model?: string;
                /** @description Filter to traces belonging to a single agent (the trace root name) — powers an agent's recent runs. */
                agent?: string;
                /** @description Filter to traces that have at least one error span. */
                has_error?: boolean;
                /** @description Return traces whose start_time_ms is after this ISO 8601 date-time. */
                start_after?: string;
                /** @description Return traces whose start_time_ms is before this ISO 8601 date-time. */
                start_before?: string;
                /** @description Page number (1-based). */
                page?: number;
                /** @description Number of results per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of traces. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTraceResponse"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getTrace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The trace_id of the trace to retrieve. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested trace with all spans. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceDetail"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Trace not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getOverviewKpis: {
        parameters: {
            query?: {
                /** @description Time window for the metric. Defaults to 7d. 24h is bucketed hourly; 7d/30d/90d/1y daily. Ranges longer than 30d (90d, 1y) are served from the daily rollup, so latency percentiles are not available for them. */
                range?: components["parameters"]["Range"];
                /** @description Optional business filter (the operator's end-client). Empty means all clients. */
                tenant_id?: components["parameters"]["TenantFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The overview KPI set. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiSet"];
                };
            };
            /** @description Invalid range. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCostSeries: {
        parameters: {
            query?: {
                /** @description Time window for the metric. Defaults to 7d. 24h is bucketed hourly; 7d/30d/90d/1y daily. Ranges longer than 30d (90d, 1y) are served from the daily rollup, so latency percentiles are not available for them. */
                range?: components["parameters"]["Range"];
                /** @description Optional business filter (the operator's end-client). Empty means all clients. */
                tenant_id?: components["parameters"]["TenantFilter"];
                /** @description Optional: restrict the metric to a single agent (the trace root name), powering the agent detail page's charts. Agent-scoped metrics are a raw-window feature — ranges longer than 30d (90d, 1y) are rejected with a 400, since per-agent latency cannot be derived from the daily rollup. */
                agent?: components["parameters"]["AgentFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cost buckets ordered by bucket_ms ascending. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCostBucketResponse"];
                };
            };
            /** @description Invalid range. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getLatencySeries: {
        parameters: {
            query?: {
                /** @description Time window for the metric. Defaults to 7d. 24h is bucketed hourly; 7d/30d/90d/1y daily. Ranges longer than 30d (90d, 1y) are served from the daily rollup, so latency percentiles are not available for them. */
                range?: components["parameters"]["Range"];
                /** @description Optional business filter (the operator's end-client). Empty means all clients. */
                tenant_id?: components["parameters"]["TenantFilter"];
                /** @description Optional: restrict the metric to a single agent (the trace root name), powering the agent detail page's charts. Agent-scoped metrics are a raw-window feature — ranges longer than 30d (90d, 1y) are rejected with a 400, since per-agent latency cannot be derived from the daily rollup. */
                agent?: components["parameters"]["AgentFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latency buckets ordered by bucket_ms ascending. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedLatencyBucketResponse"];
                };
            };
            /** @description Invalid range. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getErrorSeries: {
        parameters: {
            query?: {
                /** @description Time window for the metric. Defaults to 7d. 24h is bucketed hourly; 7d/30d/90d/1y daily. Ranges longer than 30d (90d, 1y) are served from the daily rollup, so latency percentiles are not available for them. */
                range?: components["parameters"]["Range"];
                /** @description Optional business filter (the operator's end-client). Empty means all clients. */
                tenant_id?: components["parameters"]["TenantFilter"];
                /** @description Optional: restrict the metric to a single agent (the trace root name), powering the agent detail page's charts. Agent-scoped metrics are a raw-window feature — ranges longer than 30d (90d, 1y) are rejected with a 400, since per-agent latency cannot be derived from the daily rollup. */
                agent?: components["parameters"]["AgentFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Error buckets ordered by bucket_ms ascending. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedErrorBucketResponse"];
                };
            };
            /** @description Invalid range. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getTopAgents: {
        parameters: {
            query?: {
                /** @description Time window for the metric. Defaults to 7d. 24h is bucketed hourly; 7d/30d/90d/1y daily. Ranges longer than 30d (90d, 1y) are served from the daily rollup, so latency percentiles are not available for them. */
                range?: components["parameters"]["Range"];
                /** @description Optional business filter (the operator's end-client). Empty means all clients. */
                tenant_id?: components["parameters"]["TenantFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agents ordered by cost descending. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAgentCostResponse"];
                };
            };
            /** @description Invalid range. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listAgents: {
        parameters: {
            query?: {
                /** @description Time window for the metric. Defaults to 7d. 24h is bucketed hourly; 7d/30d/90d/1y daily. Ranges longer than 30d (90d, 1y) are served from the daily rollup, so latency percentiles are not available for them. */
                range?: components["parameters"]["Range"];
                /** @description Optional business filter (the operator's end-client). Empty means all clients. */
                tenant_id?: components["parameters"]["TenantFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agents ordered by call count descending. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAgentResponse"];
                };
            };
            /** @description Invalid range. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAgentDetail: {
        parameters: {
            query?: {
                /** @description Time window for the metric. Defaults to 7d. 24h is bucketed hourly; 7d/30d/90d/1y daily. Ranges longer than 30d (90d, 1y) are served from the daily rollup, so latency percentiles are not available for them. */
                range?: components["parameters"]["Range"];
                /** @description Optional business filter (the operator's end-client). Empty means all clients. */
                tenant_id?: components["parameters"]["TenantFilter"];
            };
            header?: never;
            path: {
                /** @description The agent name (the trace root span name). */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The agent's detail payload. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDetail"];
                };
            };
            /** @description Invalid range, or a range longer than 30d. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No agent with that name has runs in the window. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getFailures: {
        parameters: {
            query?: {
                /** @description Time window for the metric. Defaults to 7d. 24h is bucketed hourly; 7d/30d/90d/1y daily. Ranges longer than 30d (90d, 1y) are served from the daily rollup, so latency percentiles are not available for them. */
                range?: components["parameters"]["Range"];
                /** @description Optional business filter (the operator's end-client). Empty means all clients. */
                tenant_id?: components["parameters"]["TenantFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Failed agents ordered by failure count descending. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedFailureResponse"];
                };
            };
            /** @description Invalid range. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status: string;
                    };
                };
            };
        };
    };
    readinessCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ready */
                        status: string;
                    };
                };
            };
            /** @description Service is not ready (e.g. database unavailable). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example not_ready */
                        status: string;
                    };
                };
            };
        };
    };
}
