/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List traces
         * @description Returns a paginated list of traces, scoped to the workspaces the caller is a member of (see workspace_id). Results are ordered by start_time_ms descending.
         */
        get: operations["listTraces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/traces/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a trace by ID
         * @description Returns a trace and spans from the caller's allowed workspaces. A known trace ID never bypasses workspace membership.
         */
        get: operations["getTrace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/traces/{traceId}/spans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List spans in an accessible trace
         * @description Returns only spans within the caller's workspace scope. A missing or inaccessible trace returns 404.
         */
        get: operations["listSpans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics/kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Overview KPIs
         * @description Returns the four headline metrics (total cost, workflow runs, p95 latency, error rate) for the selected range, each with its change versus the equal-length preceding period.
         */
        get: operations["getOverviewKpis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics/cost-series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cost over time
         * @description Total cost per time bucket across the range.
         */
        get: operations["getCostSeries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics/latency-series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latency over time
         * @description p50/p95/p99 of span duration (ms) per time bucket across the range.
         */
        get: operations["getLatencySeries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics/error-series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Failures over time
         * @description Failed-vs-total run counts per time bucket across the range — the "Failures by day" strip.
         */
        get: operations["getErrorSeries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics/top-workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Top workflows by cost
         * @description The highest-spending workflows (trace root names) in the range, ordered by cost descending.
         */
        get: operations["getTopWorkflows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Workflow activity list
         * @description Every active workflow in the range with its run count, total spend, mean run latency, error rate, and call-count sparkline — the data behind the Workflows page. Ordered by call count descending; sorting and filtering are done client-side. avg_latency_ms is 0 for long windows served from the daily rollup, where per-trace durations are not retained.
         */
        get: operations["listWorkflows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics/workflows/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Workflow detail
         * @description One workflow's detail-page payload: its headline metrics over the range plus the tool surface from its most recent run. Span-backed only — there is no workflow-config store, so runtime params (temperature, retries, version, owner, …) are not served. A raw-window feature: ranges longer than 30d (90d, 1y) are rejected with a 400, since per-workflow latency cannot be derived from the daily rollup.
         */
        get: operations["getWorkflowDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics/failures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent failures
         * @description The workflows with the most errored runs in the range. The response total counts every failed run in the window, not just the listed workflows.
         */
        get: operations["getFailures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics/anomalies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Statistical anomalies
         * @description Buckets that deviated significantly from their own recent history, for cost, error rate, and run volume — workspace-wide and per busy workflow. Detection is daily and robust (median + MAD over a trailing 28-day baseline), served entirely from the daily rollup, so a range of 7d or longer is required (24h is rejected with a 400). Results are ordered most severe first.
         */
        get: operations["getAnomalies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics/model-costs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cost by model
         * @description Spend broken down by model over the range — the usage page's "where it goes" list. Each entry carries the model's cost, run (trace) count, and summed input/output tokens, ordered by cost descending.
         */
        get: operations["getModelCosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics/usage-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Usage by user
         * @description Spend and run counts grouped by the end-client/metering user (`user.id`) over the range, each paired with the equal-length preceding window for period-over-period change, plus a per-row cost sparkline. Ordered by cost descending.
         */
        get: operations["getUserUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics/usage-workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Usage by workflow
         * @description Spend and run counts grouped by workflow over the range, each paired with the preceding window for change, plus the workflow's most-used model. Ordered by cost descending.
         */
        get: operations["getWorkflowUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics/attribute-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Custom-attribute dimensions
         * @description The custom-attribute keys present on spans in the window (e.g. `team`, `environment`, `customer`), offered as the allocation axes for /v1/metrics/usage-by-attribute.
         */
        get: operations["getAttributeKeys"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics/usage-by-attribute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cost allocation by attribute
         * @description Spend and usage allocated across the values of one custom attribute — the cost-allocation primitive that splits AI spend by whatever dimension the instrumentation tags spans with. The `key` query parameter names the dimension (from /v1/metrics/attribute-keys) and is required. Ordered by cost descending.
         */
        get: operations["getUsageByAttribute"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check
         * @description Returns 200 when the API process is running. Does not verify downstream dependencies (use /v1/ready for that).
         */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness check
         * @description Returns 200 when the API is ready to serve traffic (database connections healthy). Returns 503 when not ready.
         */
        get: operations["readinessCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register an account
         * @description Creates an account and returns a bearer token. Unauthenticated.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in
         * @description Exchanges email + password for a bearer token. Unauthenticated.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the caller's workspaces
         * @description Every workspace the authenticated account is a member of, with the account's own role in each and the workspace's member count.
         */
        get: operations["listWorkspaces"];
        put?: never;
        /**
         * Create a workspace
         * @description Creates a workspace and makes the caller its owner member.
         */
        post: operations["createWorkspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a workspace
         * @description Deletes a workspace and all its memberships. Owner only.
         */
        delete: operations["deleteWorkspace"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a member
         * @description Grants another account access to the workspace, named by email. Owner only. The member can then read the workspace's telemetry.
         */
        post: operations["addWorkspaceMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{id}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a member
         * @description Revokes an account's access. Owner only; the owner cannot be removed.
         */
        delete: operations["removeWorkspaceMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{id}/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a workspace's ingest API keys
         * @description Every API key bound to the workspace, newest first, including revoked ones (so history is visible). The secret token itself is never returned here — only its non-secret prefix and metadata. Requires membership of the workspace.
         */
        get: operations["listApiKeys"];
        put?: never;
        /**
         * Create an ingest API key
         * @description Issues a new key bound to this workspace for authenticating trace ingestion. The key both authenticates the sender and determines the workspace its telemetry lands in, so senders need not set a workspace attribute. The plaintext token is returned in this response exactly once and cannot be retrieved again — capture it now. Only its hash is stored. Requires membership of the workspace; the caller is recorded as the key's creator, for provenance only.
         */
        post: operations["createApiKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{id}/api-keys/{keyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke an ingest API key
         * @description Disables a key in this workspace. Ingest requests presenting it are rejected thereafter (subject to the collector's short verification cache). The row is retained, marked revoked, for audit. Requires membership of the workspace.
         */
        delete: operations["revokeApiKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ingest/keys/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify an ingest API key (collector-facing)
         * @description Resolves a presented ingest key to the workspace it grants. This endpoint is called by the collector's authenticator extension, not by end users, so it is unauthenticated (it carries no session) but rate-limited. It leaks no detail about why a key failed.
         */
        post: operations["verifyApiKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Credentials: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        Token: {
            /** @description Bearer token to send as the Authorization: Bearer header. */
            token: string;
        };
        Workspace: {
            id: string;
            name: string;
            slug: string;
            /** @enum {string} */
            env: "production" | "staging" | "development";
            /**
             * @description The calling account's role in this workspace.
             * @enum {string}
             */
            role: "owner" | "member";
            /** @description Total number of accounts with access to this workspace. */
            members: number;
        };
        WorkspaceInput: {
            name: string;
            slug: string;
            /** @enum {string} */
            env: "production" | "staging" | "development";
        };
        AddMemberInput: {
            /**
             * Format: email
             * @description The account to grant access to.
             */
            email: string;
            /**
             * @default member
             * @enum {string}
             */
            role: "owner" | "member";
        };
        APIKey: {
            /** Format: uuid */
            id: string;
            /** @description The workspace this key is bound to and ingests into. */
            workspace_id: string;
            /** @description The account that created the key, for provenance only. It carries no authority — the key keeps working regardless of this account. */
            created_by: string;
            /** @description Human label for the key. */
            name: string;
            /** @description Non-secret leading slice of the token (e.g. "trc_9f3a1b2c"), shown so the key is identifiable in the UI without revealing it. */
            prefix: string;
            /** Format: date-time */
            created_at: string;
            /**
             * Format: date-time
             * @description When the key was last accepted at ingest, or null if never.
             */
            last_used_at?: string | null;
            /**
             * Format: date-time
             * @description When the key was revoked, or null if still active.
             */
            revoked_at?: string | null;
        };
        APIKeyInput: {
            /** @description Optional label; defaults to "default" when omitted. */
            name?: string;
        };
        APIKeyCreated: {
            key: components["schemas"]["APIKey"];
            /** @description The plaintext ingest key (e.g. "trc_..."). Returned only here, only once; it is stored hashed and cannot be recovered later. Send it as "Authorization: Bearer <token>" on OTLP ingest. */
            token: string;
        };
        APIKeyVerifyRequest: {
            /** @description The plaintext ingest key to verify. */
            key: string;
        };
        APIKeyVerifyResponse: {
            /** @description The workspace the key grants. The collector stamps this onto every span the request carries, overriding any sender-supplied workspace — the key, not the payload, decides where data lands. */
            workspace_id: string;
        };
        Span: {
            /** @description Globally unique identifier for the trace this span belongs to. */
            trace_id: string;
            /** @description Globally unique identifier for this span. */
            span_id: string;
            /** @description span_id of the parent span, if this is a child span. */
            parent_span_id?: string;
            /** @description Human-readable name for this span. */
            name: string;
            /** @description Unix epoch milliseconds when the span started. */
            start_time_ms?: number;
            /** @description Unix epoch milliseconds when the span ended. */
            end_time_ms?: number;
            /** @description Duration of the span in milliseconds. */
            duration_ms?: number;
            /** @description The model name as reported in gen_ai.request.model. */
            model?: string;
            /** @description Why the model stopped generating. */
            finish_reason?: string;
            /** @description Number of input tokens consumed. */
            input_tokens?: number;
            /** @description Number of output tokens generated. */
            output_tokens?: number;
            /** @description Computed cost in USD for this span. */
            cost_usd?: number;
            /** @description End-client / user identifier — the metering & cost-attribution label (not an access boundary). */
            user_id?: string;
            /** @description Workspace the span belongs to — the access-control unit (accounts read only workspaces they are a member of). */
            workspace_id?: string;
            /** @description Canonical model id after alias resolution. */
            model_normalized?: string;
            /** @description Schema version of this span record. */
            schema_version?: number;
            /** @description Added in schema v2. Short error class or type. */
            error_type?: string;
            /** @description Added in schema v2. Human-readable error message if the span failed. */
            error_message?: string;
            /**
             * @description Normalized span role, derived by the collector from instrumentation attributes (OpenInference openinference.span.kind, Traceloop traceloop.span.kind, or the OTel GenAI gen_ai.operation.name). Optional: omitted when the collector could not classify the span, in which case consumers infer the role from the span's context.
             * @enum {string}
             */
            kind?: "agent" | "llm" | "tool" | "chain" | "retriever" | "embedding";
        };
        Trace: {
            /** @description Globally unique identifier for this trace. */
            trace_id: string;
            /** @description Human-readable name for the trace. */
            name?: string;
            /** @description Unix epoch milliseconds when the trace started. */
            start_time_ms?: number;
            /** @description Unix epoch milliseconds when the trace ended. */
            end_time_ms?: number;
            /** @description Total duration in milliseconds. */
            duration_ms?: number;
            /** @description End-client / user identifier — the metering & cost-attribution label (not an access boundary). */
            user_id?: string;
            /** @description Workspace the trace belongs to — the access-control unit. */
            workspace_id?: string;
            /** @description Total number of spans in this trace. */
            span_count?: number;
            /** @description True if any span in this trace recorded an error. */
            has_error?: boolean;
            /** @description Sum of cost_usd across all spans in this trace. */
            total_cost_usd?: number;
            /** @description Schema version of this trace record. */
            schema_version?: number;
        };
        TraceDetail: components["schemas"]["Trace"] & {
            /** @description All spans belonging to this trace, ordered by start_time_ms ascending. */
            spans: components["schemas"]["Span"][];
        };
        ErrorResponse: {
            /** @description Machine-readable error code (e.g. NOT_FOUND, UNAUTHORIZED, INVALID_REQUEST). */
            code: string;
            /** @description Human-readable description of the error. */
            message: string;
        };
        PaginatedSpanResponse: {
            items: components["schemas"]["Span"][];
            total: number;
            page: number;
            page_size: number;
        };
        PaginatedTraceResponse: {
            /** @description The traces on this page. */
            items: components["schemas"]["Trace"][];
            /** @description Total number of matching traces across all pages. */
            total: number;
            /** @description Current page number (1-based). */
            page: number;
            /** @description Number of items per page. */
            page_size: number;
            /** @description True if there are more pages after this one. */
            has_more: boolean;
        };
        Kpi: {
            /** @description Raw metric value (USD, count, ms, or fraction depending on the KPI). */
            value: number;
            /** @description Fractional change versus the preceding period (0.12 == +12%). */
            delta: number;
            /**
             * @description Whether the change is favourable, given the metric's direction.
             * @enum {string}
             */
            delta_type: "good" | "bad" | "neutral";
        };
        KpiSet: {
            /** @description Total cost in USD. */
            cost: components["schemas"]["Kpi"];
            /** @description Workflow runs (distinct traces). */
            runs: components["schemas"]["Kpi"];
            /** @description p95 trace duration in ms. */
            latency_p95: components["schemas"]["Kpi"];
            /** @description Fraction of traces with an error. */
            error_rate: components["schemas"]["Kpi"];
        };
        CostBucket: {
            /** @description Bucket start, Unix epoch milliseconds. */
            bucket_ms: number;
            /** @description Total cost in USD within the bucket. */
            value: number;
            /** @description True if the bucket exceeds three times the window's median. */
            anomaly: boolean;
        };
        ErrorBucket: {
            /** @description Bucket start, Unix epoch milliseconds. */
            bucket_ms: number;
            /** @description Runs that errored within the bucket. */
            errors: number;
            /** @description Total runs that started within the bucket. */
            total: number;
        };
        LatencyBucket: {
            /** @description Bucket start, Unix epoch milliseconds. */
            bucket_ms: number;
            /** @description Median span duration in the bucket, ms. Null when no runs fell in the bucket (latency is undefined rather than 0). */
            p50: number | null;
            /** @description 95th-percentile span duration in the bucket, ms. Null when no runs fell in the bucket. */
            p95: number | null;
            /** @description 99th-percentile span duration in the bucket, ms. Null when no runs fell in the bucket. */
            p99: number | null;
        };
        WorkflowCost: {
            /** @description Workflow name (the trace root span name). */
            name: string;
            /** @description Total cost in USD over the window. */
            cost: number;
            /** @description Number of runs (traces) for this workflow. */
            calls: number;
            /** @description Call count per time bucket across the window, oldest first and zero-filled, aligned to a shared axis for the usage sparkline. */
            trend: number[];
        };
        Workflow: {
            /** @description Workflow name (the trace root span name). */
            name: string;
            /** @description Number of runs (traces) for this workflow over the window. */
            calls: number;
            /** @description Total cost in USD over the window. */
            cost: number;
            /** @description Mean end-to-end run duration in milliseconds. 0 for long windows served from the daily rollup, where per-trace durations are not retained. */
            avg_latency_ms: number;
            /** @description Fraction of the workflow's runs that errored (0–1). */
            error_rate: number;
            /** @description Call count per time bucket across the window, oldest first and zero-filled, aligned to a shared axis for the row sparkline. */
            trend: number[];
            /** @description The workflow's most recent trace in the window, for deep-linking a row to its trace detail. Empty for long windows served from the daily rollup, which does not retain trace identity. */
            last_trace_id: string;
        };
        AvailableTool: {
            /** @description Tool name as offered to the model. */
            name: string;
            /** @description Whether the workflow invoked this tool in the sampled run. */
            used: boolean;
            /** @description Human-readable description of what the tool does. */
            description?: string;
        };
        WorkflowDetail: {
            /** @description Workflow name (the trace root span name). */
            name: string;
            /** @description Number of runs (traces) for this workflow over the window. */
            calls: number;
            /** @description Total cost in USD over the window. */
            cost: number;
            /** @description Mean end-to-end run duration in milliseconds. */
            avg_latency_ms: number;
            /** @description p95 end-to-end run duration in milliseconds, or null when undefined (no runs in the window). */
            p95_latency_ms: number | null;
            /** @description Fraction of the workflow's runs that errored (0–1). */
            error_rate: number;
            /** @description Total input tokens across the workflow's runs over the window. */
            input_tokens: number;
            /** @description Total output tokens across the workflow's runs over the window. */
            output_tokens: number;
            /** @description The workflow's most-used normalized model id over the window. */
            model: string;
            /** @description Provider inferred from the model id; empty when unrecognised. */
            provider: string;
            /** @description The workflow's tool surface — the union of available_tools from its most recent run. Empty when content/tool capture is disabled. */
            tools: components["schemas"]["AvailableTool"][];
            /** @description The workflow's most recent trace in the window, for deep-linking. */
            last_trace_id: string;
        };
        Failure: {
            /** @description Workflow name (the trace root span name). */
            workflow: string;
            /** @description Number of failed runs. */
            count: number;
            /** @description Fraction of this workflow's runs that failed. */
            pct: number;
            /** @description Most common error_type among this workflow's failed runs. */
            top_error: string;
        };
        PaginatedCostBucketResponse: {
            items: components["schemas"]["CostBucket"][];
            total: number;
            page: number;
            page_size: number;
        };
        PaginatedErrorBucketResponse: {
            items: components["schemas"]["ErrorBucket"][];
            total: number;
            page: number;
            page_size: number;
        };
        PaginatedLatencyBucketResponse: {
            items: components["schemas"]["LatencyBucket"][];
            total: number;
            page: number;
            page_size: number;
        };
        PaginatedWorkflowCostResponse: {
            items: components["schemas"]["WorkflowCost"][];
            total: number;
            page: number;
            page_size: number;
        };
        PaginatedWorkflowResponse: {
            items: components["schemas"]["Workflow"][];
            total: number;
            page: number;
            page_size: number;
        };
        PaginatedFailureResponse: {
            items: components["schemas"]["Failure"][];
            /** @description Total failed runs in the window (not just the listed workflows). */
            total: number;
            page: number;
            page_size: number;
        };
        Anomaly: {
            /**
             * @description The metric that deviated.
             * @enum {string}
             */
            metric: "cost" | "error_rate" | "runs";
            /**
             * @description Whether this anomaly is workspace-wide or for one workflow.
             * @enum {string}
             */
            scope: "workspace" | "workflow";
            /** @description The workflow name when scope is "workflow"; empty otherwise. */
            workflow: string;
            /** @description Anomalous day bucket, Unix epoch milliseconds (UTC midnight). */
            bucket_ms: number;
            /** @description The bucket's value (USD, error rate 0–1, or run count). */
            observed: number;
            /** @description Baseline median the value was compared against. */
            expected: number;
            /** @description observed − expected. */
            deviation: number;
            /** @description Signed robust z-score (0.6745·deviation/MAD); its sign matches direction. */
            score: number;
            /**
             * @description Whether the value rose above or fell below the baseline.
             * @enum {string}
             */
            direction: "spike" | "drop";
            /**
             * @description Magnitude band of the deviation.
             * @enum {string}
             */
            severity: "info" | "warning" | "critical";
            /** @description One-line human-readable description of the anomaly. */
            summary: string;
        };
        PaginatedAnomalyResponse: {
            items: components["schemas"]["Anomaly"][];
            total: number;
            page: number;
            page_size: number;
        };
        ModelCost: {
            /** @description Model id. */
            name: string;
            /** @description Total cost in USD over the window. */
            cost: number;
            /** @description Number of runs (traces) attributed to this model. */
            calls: number;
            /** @description Input tokens summed across the model's spans. */
            input_tokens: number;
            /** @description Output tokens summed across the model's spans. */
            output_tokens: number;
        };
        UserUsage: {
            /** @description The end-client/metering user (from the `user.id` attribute). */
            user_id: string;
            /** @description Cost in USD over the current window. */
            cost: number;
            /** @description Cost in USD over the equal-length preceding window. */
            cost_prev: number;
            /** @description Run (trace) count over the current window. */
            runs: number;
            /** @description Run count over the preceding window. */
            runs_prev: number;
            /** @description Cost per time bucket across the current window, oldest first and zero-filled, for the row sparkline. */
            trend: number[];
        };
        WorkflowUsage: {
            /** @description Workflow name (the trace root span name). */
            name: string;
            /** @description The workflow's most-used model over the window. */
            model: string;
            /** @description Cost in USD over the current window. */
            cost: number;
            /** @description Cost in USD over the equal-length preceding window. */
            cost_prev: number;
            /** @description Run (trace) count over the current window. */
            runs: number;
            /** @description Run count over the preceding window. */
            runs_prev: number;
        };
        AttributeUsage: {
            /** @description One value of the grouped custom attribute. */
            value: string;
            /** @description Total cost in USD over the window for this value. */
            cost: number;
            /** @description Number of spans attributed to this value. */
            calls: number;
            /** @description Number of runs (traces) attributed to this value. */
            runs: number;
            /** @description Input tokens summed across this value's spans. */
            input_tokens: number;
            /** @description Output tokens summed across this value's spans. */
            output_tokens: number;
        };
        PaginatedModelCostResponse: {
            items: components["schemas"]["ModelCost"][];
            total: number;
            page: number;
            page_size: number;
        };
        PaginatedUserUsageResponse: {
            items: components["schemas"]["UserUsage"][];
            total: number;
            page: number;
            page_size: number;
        };
        PaginatedWorkflowUsageResponse: {
            items: components["schemas"]["WorkflowUsage"][];
            total: number;
            page: number;
            page_size: number;
        };
        PaginatedAttributeKeyResponse: {
            /** @description Available custom-attribute keys. */
            items: string[];
            total: number;
            page: number;
            page_size: number;
        };
        PaginatedAttributeUsageResponse: {
            items: components["schemas"]["AttributeUsage"][];
            total: number;
            page: number;
            page_size: number;
        };
    };
    responses: never;
    parameters: {
        /** @description Time window for the metric. Defaults to 7d. 24h is bucketed hourly; 7d/30d/90d/1y daily. Ranges longer than 30d (90d, 1y) are served from the daily rollup, so latency percentiles are not available for them. */
        Range: "24h" | "7d" | "30d" | "90d" | "1y";
        /** @description Optional business filter (the operator's end-client). Empty means all clients. */
        UserFilter: string;
        /** @description Scope the read to one workspace. This is an access boundary, not just a filter: the caller must be a member of the workspace or the request is refused with 403. Omitted, the read covers every workspace the caller is a member of (an account that is a member of none sees nothing). The dashboard passes the active workspace from its switcher. */
        WorkspaceFilter: string;
        /** @description Optional: restrict the metric to a single workflow (the trace root name), powering the workflow detail page's charts. Workflow-scoped metrics are a raw-window feature — ranges longer than 30d (90d, 1y) are rejected with a 400, since per-workflow latency cannot be derived from the daily rollup. */
        WorkflowFilter: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listTraces: {
        parameters: {
            query?: {
                /** @description Optional filter by end-client / user id (a metering label, not an access boundary). */
                user_id?: string;
                /** @description Scope the read to one workspace. This is an access boundary, not just a filter: the caller must be a member of the workspace or the request is refused with 403. Omitted, the read covers every workspace the caller is a member of (an account that is a member of none sees nothing). The dashboard passes the active workspace from its switcher. */
                workspace_id?: components["parameters"]["WorkspaceFilter"];
                /** @description Filter traces that contain at least one span using this model (normalized model id). */
                model?: string;
                /** @description Filter to traces belonging to a single workflow (the trace root name) — powers an workflow's recent runs. */
                workflow?: string;
                /** @description Filter to traces that have at least one error span. */
                has_error?: boolean;
                /** @description Return traces whose start_time_ms is after this ISO 8601 date-time. */
                start_after?: string;
                /** @description Return traces whose start_time_ms is before this ISO 8601 date-time. */
                start_before?: string;
                /** @description Page number (1-based). */
                page?: number;
                /** @description Number of results per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of traces. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTraceResponse"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getTrace: {
        parameters: {
            query?: {
                /** @description Scope the read to one workspace. This is an access boundary, not just a filter: the caller must be a member of the workspace or the request is refused with 403. Omitted, the read covers every workspace the caller is a member of (an account that is a member of none sees nothing). The dashboard passes the active workspace from its switcher. */
                workspace_id?: components["parameters"]["WorkspaceFilter"];
            };
            header?: never;
            path: {
                /** @description The trace_id of the trace to retrieve. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested trace with all spans. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceDetail"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The requested workspace is inaccessible. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Trace not found in the caller's workspace scope. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listSpans: {
        parameters: {
            query?: {
                /** @description Scope the read to one workspace. This is an access boundary, not just a filter: the caller must be a member of the workspace or the request is refused with 403. Omitted, the read covers every workspace the caller is a member of (an account that is a member of none sees nothing). The dashboard passes the active workspace from its switcher. */
                workspace_id?: components["parameters"]["WorkspaceFilter"];
            };
            header?: never;
            path: {
                traceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Spans from accessible workspaces. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSpanResponse"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The requested workspace is inaccessible. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No accessible spans for that trace ID. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal error or incompatible span schema. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getOverviewKpis: {
        parameters: {
            query?: {
                /** @description Time window for the metric. Defaults to 7d. 24h is bucketed hourly; 7d/30d/90d/1y daily. Ranges longer than 30d (90d, 1y) are served from the daily rollup, so latency percentiles are not available for them. */
                range?: components["parameters"]["Range"];
                /** @description Optional business filter (the operator's end-client). Empty means all clients. */
                user_id?: components["parameters"]["UserFilter"];
                /** @description Scope the read to one workspace. This is an access boundary, not just a filter: the caller must be a member of the workspace or the request is refused with 403. Omitted, the read covers every workspace the caller is a member of (an account that is a member of none sees nothing). The dashboard passes the active workspace from its switcher. */
                workspace_id?: components["parameters"]["WorkspaceFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The overview KPI set. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiSet"];
                };
            };
            /** @description Invalid range. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCostSeries: {
        parameters: {
            query?: {
                /** @description Time window for the metric. Defaults to 7d. 24h is bucketed hourly; 7d/30d/90d/1y daily. Ranges longer than 30d (90d, 1y) are served from the daily rollup, so latency percentiles are not available for them. */
                range?: components["parameters"]["Range"];
                /** @description Optional business filter (the operator's end-client). Empty means all clients. */
                user_id?: components["parameters"]["UserFilter"];
                /** @description Scope the read to one workspace. This is an access boundary, not just a filter: the caller must be a member of the workspace or the request is refused with 403. Omitted, the read covers every workspace the caller is a member of (an account that is a member of none sees nothing). The dashboard passes the active workspace from its switcher. */
                workspace_id?: components["parameters"]["WorkspaceFilter"];
                /** @description Optional: restrict the metric to a single workflow (the trace root name), powering the workflow detail page's charts. Workflow-scoped metrics are a raw-window feature — ranges longer than 30d (90d, 1y) are rejected with a 400, since per-workflow latency cannot be derived from the daily rollup. */
                workflow?: components["parameters"]["WorkflowFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cost buckets ordered by bucket_ms ascending. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCostBucketResponse"];
                };
            };
            /** @description Invalid range. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getLatencySeries: {
        parameters: {
            query?: {
                /** @description Time window for the metric. Defaults to 7d. 24h is bucketed hourly; 7d/30d/90d/1y daily. Ranges longer than 30d (90d, 1y) are served from the daily rollup, so latency percentiles are not available for them. */
                range?: components["parameters"]["Range"];
                /** @description Optional business filter (the operator's end-client). Empty means all clients. */
                user_id?: components["parameters"]["UserFilter"];
                /** @description Scope the read to one workspace. This is an access boundary, not just a filter: the caller must be a member of the workspace or the request is refused with 403. Omitted, the read covers every workspace the caller is a member of (an account that is a member of none sees nothing). The dashboard passes the active workspace from its switcher. */
                workspace_id?: components["parameters"]["WorkspaceFilter"];
                /** @description Optional: restrict the metric to a single workflow (the trace root name), powering the workflow detail page's charts. Workflow-scoped metrics are a raw-window feature — ranges longer than 30d (90d, 1y) are rejected with a 400, since per-workflow latency cannot be derived from the daily rollup. */
                workflow?: components["parameters"]["WorkflowFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latency buckets ordered by bucket_ms ascending. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedLatencyBucketResponse"];
                };
            };
            /** @description Invalid range. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getErrorSeries: {
        parameters: {
            query?: {
                /** @description Time window for the metric. Defaults to 7d. 24h is bucketed hourly; 7d/30d/90d/1y daily. Ranges longer than 30d (90d, 1y) are served from the daily rollup, so latency percentiles are not available for them. */
                range?: components["parameters"]["Range"];
                /** @description Optional business filter (the operator's end-client). Empty means all clients. */
                user_id?: components["parameters"]["UserFilter"];
                /** @description Scope the read to one workspace. This is an access boundary, not just a filter: the caller must be a member of the workspace or the request is refused with 403. Omitted, the read covers every workspace the caller is a member of (an account that is a member of none sees nothing). The dashboard passes the active workspace from its switcher. */
                workspace_id?: components["parameters"]["WorkspaceFilter"];
                /** @description Optional: restrict the metric to a single workflow (the trace root name), powering the workflow detail page's charts. Workflow-scoped metrics are a raw-window feature — ranges longer than 30d (90d, 1y) are rejected with a 400, since per-workflow latency cannot be derived from the daily rollup. */
                workflow?: components["parameters"]["WorkflowFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Error buckets ordered by bucket_ms ascending. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedErrorBucketResponse"];
                };
            };
            /** @description Invalid range. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getTopWorkflows: {
        parameters: {
            query?: {
                /** @description Time window for the metric. Defaults to 7d. 24h is bucketed hourly; 7d/30d/90d/1y daily. Ranges longer than 30d (90d, 1y) are served from the daily rollup, so latency percentiles are not available for them. */
                range?: components["parameters"]["Range"];
                /** @description Optional business filter (the operator's end-client). Empty means all clients. */
                user_id?: components["parameters"]["UserFilter"];
                /** @description Scope the read to one workspace. This is an access boundary, not just a filter: the caller must be a member of the workspace or the request is refused with 403. Omitted, the read covers every workspace the caller is a member of (an account that is a member of none sees nothing). The dashboard passes the active workspace from its switcher. */
                workspace_id?: components["parameters"]["WorkspaceFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workflows ordered by cost descending. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedWorkflowCostResponse"];
                };
            };
            /** @description Invalid range. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listWorkflows: {
        parameters: {
            query?: {
                /** @description Time window for the metric. Defaults to 7d. 24h is bucketed hourly; 7d/30d/90d/1y daily. Ranges longer than 30d (90d, 1y) are served from the daily rollup, so latency percentiles are not available for them. */
                range?: components["parameters"]["Range"];
                /** @description Optional business filter (the operator's end-client). Empty means all clients. */
                user_id?: components["parameters"]["UserFilter"];
                /** @description Scope the read to one workspace. This is an access boundary, not just a filter: the caller must be a member of the workspace or the request is refused with 403. Omitted, the read covers every workspace the caller is a member of (an account that is a member of none sees nothing). The dashboard passes the active workspace from its switcher. */
                workspace_id?: components["parameters"]["WorkspaceFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workflows ordered by call count descending. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedWorkflowResponse"];
                };
            };
            /** @description Invalid range. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getWorkflowDetail: {
        parameters: {
            query?: {
                /** @description Time window for the metric. Defaults to 7d. 24h is bucketed hourly; 7d/30d/90d/1y daily. Ranges longer than 30d (90d, 1y) are served from the daily rollup, so latency percentiles are not available for them. */
                range?: components["parameters"]["Range"];
                /** @description Optional business filter (the operator's end-client). Empty means all clients. */
                user_id?: components["parameters"]["UserFilter"];
                /** @description Scope the read to one workspace. This is an access boundary, not just a filter: the caller must be a member of the workspace or the request is refused with 403. Omitted, the read covers every workspace the caller is a member of (an account that is a member of none sees nothing). The dashboard passes the active workspace from its switcher. */
                workspace_id?: components["parameters"]["WorkspaceFilter"];
            };
            header?: never;
            path: {
                /** @description The workflow name (the trace root span name). */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The workflow's detail payload. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDetail"];
                };
            };
            /** @description Invalid range, or a range longer than 30d. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No workflow with that name has runs in the window. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getFailures: {
        parameters: {
            query?: {
                /** @description Time window for the metric. Defaults to 7d. 24h is bucketed hourly; 7d/30d/90d/1y daily. Ranges longer than 30d (90d, 1y) are served from the daily rollup, so latency percentiles are not available for them. */
                range?: components["parameters"]["Range"];
                /** @description Optional business filter (the operator's end-client). Empty means all clients. */
                user_id?: components["parameters"]["UserFilter"];
                /** @description Scope the read to one workspace. This is an access boundary, not just a filter: the caller must be a member of the workspace or the request is refused with 403. Omitted, the read covers every workspace the caller is a member of (an account that is a member of none sees nothing). The dashboard passes the active workspace from its switcher. */
                workspace_id?: components["parameters"]["WorkspaceFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Failed workflows ordered by failure count descending. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedFailureResponse"];
                };
            };
            /** @description Invalid range. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAnomalies: {
        parameters: {
            query?: {
                /** @description Time window for the metric. Defaults to 7d. 24h is bucketed hourly; 7d/30d/90d/1y daily. Ranges longer than 30d (90d, 1y) are served from the daily rollup, so latency percentiles are not available for them. */
                range?: components["parameters"]["Range"];
                /** @description Optional business filter (the operator's end-client). Empty means all clients. */
                user_id?: components["parameters"]["UserFilter"];
                /** @description Scope the read to one workspace. This is an access boundary, not just a filter: the caller must be a member of the workspace or the request is refused with 403. Omitted, the read covers every workspace the caller is a member of (an account that is a member of none sees nothing). The dashboard passes the active workspace from its switcher. */
                workspace_id?: components["parameters"]["WorkspaceFilter"];
                /** @description Restrict to one metric. Omitted, all three are detected. */
                metric?: "cost" | "error_rate" | "runs";
                /** @description Drop anomalies below this severity. Omitted, all severities are returned. */
                min_severity?: "info" | "warning" | "critical";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Anomalies ordered by severity, then score, then recency. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAnomalyResponse"];
                };
            };
            /** @description Invalid range, metric, or severity. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getModelCosts: {
        parameters: {
            query?: {
                /** @description Time window for the metric. Defaults to 7d. 24h is bucketed hourly; 7d/30d/90d/1y daily. Ranges longer than 30d (90d, 1y) are served from the daily rollup, so latency percentiles are not available for them. */
                range?: components["parameters"]["Range"];
                /** @description Optional business filter (the operator's end-client). Empty means all clients. */
                user_id?: components["parameters"]["UserFilter"];
                /** @description Scope the read to one workspace. This is an access boundary, not just a filter: the caller must be a member of the workspace or the request is refused with 403. Omitted, the read covers every workspace the caller is a member of (an account that is a member of none sees nothing). The dashboard passes the active workspace from its switcher. */
                workspace_id?: components["parameters"]["WorkspaceFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Models ordered by cost descending. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedModelCostResponse"];
                };
            };
            /** @description Invalid range. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getUserUsage: {
        parameters: {
            query?: {
                /** @description Time window for the metric. Defaults to 7d. 24h is bucketed hourly; 7d/30d/90d/1y daily. Ranges longer than 30d (90d, 1y) are served from the daily rollup, so latency percentiles are not available for them. */
                range?: components["parameters"]["Range"];
                /** @description Optional business filter (the operator's end-client). Empty means all clients. */
                user_id?: components["parameters"]["UserFilter"];
                /** @description Scope the read to one workspace. This is an access boundary, not just a filter: the caller must be a member of the workspace or the request is refused with 403. Omitted, the read covers every workspace the caller is a member of (an account that is a member of none sees nothing). The dashboard passes the active workspace from its switcher. */
                workspace_id?: components["parameters"]["WorkspaceFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Users ordered by cost descending. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUserUsageResponse"];
                };
            };
            /** @description Invalid range. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getWorkflowUsage: {
        parameters: {
            query?: {
                /** @description Time window for the metric. Defaults to 7d. 24h is bucketed hourly; 7d/30d/90d/1y daily. Ranges longer than 30d (90d, 1y) are served from the daily rollup, so latency percentiles are not available for them. */
                range?: components["parameters"]["Range"];
                /** @description Optional business filter (the operator's end-client). Empty means all clients. */
                user_id?: components["parameters"]["UserFilter"];
                /** @description Scope the read to one workspace. This is an access boundary, not just a filter: the caller must be a member of the workspace or the request is refused with 403. Omitted, the read covers every workspace the caller is a member of (an account that is a member of none sees nothing). The dashboard passes the active workspace from its switcher. */
                workspace_id?: components["parameters"]["WorkspaceFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workflows ordered by cost descending. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedWorkflowUsageResponse"];
                };
            };
            /** @description Invalid range. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAttributeKeys: {
        parameters: {
            query?: {
                /** @description Time window for the metric. Defaults to 7d. 24h is bucketed hourly; 7d/30d/90d/1y daily. Ranges longer than 30d (90d, 1y) are served from the daily rollup, so latency percentiles are not available for them. */
                range?: components["parameters"]["Range"];
                /** @description Optional business filter (the operator's end-client). Empty means all clients. */
                user_id?: components["parameters"]["UserFilter"];
                /** @description Scope the read to one workspace. This is an access boundary, not just a filter: the caller must be a member of the workspace or the request is refused with 403. Omitted, the read covers every workspace the caller is a member of (an account that is a member of none sees nothing). The dashboard passes the active workspace from its switcher. */
                workspace_id?: components["parameters"]["WorkspaceFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available attribute keys. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAttributeKeyResponse"];
                };
            };
            /** @description Invalid range. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getUsageByAttribute: {
        parameters: {
            query: {
                /** @description The custom-attribute key to group by (e.g. "team"). */
                key: string;
                /** @description Time window for the metric. Defaults to 7d. 24h is bucketed hourly; 7d/30d/90d/1y daily. Ranges longer than 30d (90d, 1y) are served from the daily rollup, so latency percentiles are not available for them. */
                range?: components["parameters"]["Range"];
                /** @description Optional business filter (the operator's end-client). Empty means all clients. */
                user_id?: components["parameters"]["UserFilter"];
                /** @description Scope the read to one workspace. This is an access boundary, not just a filter: the caller must be a member of the workspace or the request is refused with 403. Omitted, the read covers every workspace the caller is a member of (an account that is a member of none sees nothing). The dashboard passes the active workspace from its switcher. */
                workspace_id?: components["parameters"]["WorkspaceFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attribute values ordered by cost descending. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAttributeUsageResponse"];
                };
            };
            /** @description Invalid range, or the required `key` parameter is missing. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status: string;
                    };
                };
            };
        };
    };
    readinessCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ready */
                        status: string;
                    };
                };
            };
            /** @description Service is not ready (e.g. database unavailable). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example not_ready */
                        status: string;
                    };
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Account created; token returned. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description An account with that email already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Authenticated; token returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listWorkspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's workspaces. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"][];
                };
            };
        };
    };
    createWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceInput"];
            };
        };
        responses: {
            /** @description The created workspace. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
        };
    };
    deleteWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such workspace owned by the caller. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    addWorkspaceMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemberInput"];
            };
        };
        responses: {
            /** @description Member added (idempotent). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Workspace not owned by the caller, or no account with that email. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    removeWorkspaceMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Member removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Attempted to remove the owner. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Workspace not owned by the caller, or member not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listApiKeys: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The workspace's API keys (metadata only). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIKey"][];
                };
            };
            /** @description The caller is not a member of the workspace. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["APIKeyInput"];
            };
        };
        responses: {
            /** @description The created key, including the one-time plaintext token. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIKeyCreated"];
                };
            };
            /** @description The caller is not a member of the workspace. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    revokeApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                keyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The caller is not a member of the workspace. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No such active key in this workspace. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    verifyApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["APIKeyVerifyRequest"];
            };
        };
        responses: {
            /** @description The key is valid; the workspace it grants is returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIKeyVerifyResponse"];
                };
            };
            /** @description The key is missing, malformed, unknown, or revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
